server {
 listen 80;
 server_name _;
 root /usr/share/nginx/html;
 index index.html;
 charset utf-8;
 add_header X-Robots-Tag "noindex, nofollow" always;
 location / {
  try_files $uri $uri/ /index.html;
  add_header Cache-Control "no-cache, max-age=0, must-revalidate" always;
  add_header X-Robots-Tag "noindex, nofollow" always;
 }
 location ~* \.(webp|png|jpg|svg|woff2|ico)$ {
  expires 7d;
  add_header X-Robots-Tag "noindex, nofollow" always;
 }
}
